---
title: "Untitled"
output: html_document
---

```{r}
library(tidyverse)
library(ggmap)
library(viridis)
library(tree)
library(lubridate)
library(randomForest)
library(party)
```

```{r}
taxi <- read_csv("taxi.csv")
manhattan <- readRDS("manhattan.rds")
```


2. Cleaning the taxi data
```{r}
# Renaming the location variables,
# dropping any journeys with zero fares and zero tips,
# and creating the total variable as the log sum of fare and tip
taxi <- taxi %>%
  rename(long = pickup_longitude, lat = pickup_latitude) %>%
  filter(fare_amount>0| tip_amount>0) %>%
  mutate(total = log(fare_amount + tip_amount)) # We use log to reduce the skew
```

3. Zooming in on Manhattan
```{r}
# Reducing the data to taxi trips starting in Manhattan
# Manhattan is bounded by the rectangle with 
# latitude from 40.70 to 40.83 and 
# longitude from -74.025 to -73.93
taxi <- taxi %>%
  filter(between(lat, 40.70, 40.83), between(long, -74.025, -73.93))
```

4. Where does the journey begin?
```{r}
# Drawing a density map with the number of journey start locations
ggmap(manhattan, darken = 0.5) +
  scale_fill_viridis(option = "plasma") +
  geom_bin2d(data = taxi, aes(x = long, y = lat), bins = 60, alpha=0.6) +
  labs(x = "Longitude", y = "Latitude", fill = "Rides", title = "Number of Rides Start Locations")
```

5. Predicting taxi fares using a tree
```{r}
# Fitting a tree to lat and long
fitted_tree <- tree(total ~ lat + long, data = taxi)

# Draw a diagram of the tree structure
plot(fitted_tree)
text(fitted_tree)
```

6. It's time. More predictors.
```{r}
# Generate the three new time variables
taxi <- taxi %>%
  mutate(hour = hour(pickup_datetime),
         wday = wday(pickup_datetime, label = TRUE),
         month = month(pickup_datetime,label = TRUE))
```

7. One more tree!¶
```{r}
# Fitting a tree with total as the outcome and 
# lat, long, hour, wday, and month as predictors
fitted_tree <- tree(total~lat + long+hour+wday+month, data = taxi)

# Draw a diagram of the tree structure
plot(fitted_tree)
text(fitted_tree)

# Summarizing the performance of the tree
summary(fitted_tree)
```

8. One tree is not enough
```{r}
# Fitting a random forest
fitted_forest <-  randomForest(total~lat + long+hour+wday+month, data=taxi, ntree=80, sampsize = 10000)

# Printing the fitted_forest object
summary(fitted_forest)
```

```{r}
x <- ctree(total~lat + long+hour+wday+month, data=taxi)
plot(x, type = "simple") 
```

9. Plotting the predicted fare
```{r}
# Extracting the prediction from fitted_forest
taxi$pred_total <- fitted_forest$predicted

# Plotting the predicted mean trip prices from according to the random forest
# Drawing a density map with the number of journey start locations
ggmap(manhattan, darken = 0.5) +
  scale_fill_viridis(option = "plasma") +
  stat_summary_2d(data = taxi, aes(x=long, y = lat, z =pred_total), bins = 60, alpha = 0.6, fun = mean)+
  labs(x="Longitude", y = "Latitude", fill = "Log fare + tip", title = "Predictions Number of Rides Start Locations ")
```

10. Plotting the actual fare
```{r}
# Funtion that returns the mean *if* there are 15 or more datapoints
mean_if_enough_data <- function(x) {
  ifelse(length(x)>=15, mean(x), NA)
}

# Plotting the mean trip prices fron the data
ggmap(manhattan, darken = 0.5) +
  scale_fill_viridis(option = "plasma") +
  stat_summary_2d(data = taxi, aes(x=long, y = lat, z =pred_total), bins = 60, alpha = 0.6, fun = mean_if_enough_data)+
  labs(x="Longitude", y = "Latitude", fill = "Log fare + tip", title = "Predictions Number of Rides Start Locations Over Time")
```

11. Where do people spend the most?¶
```{r}
# Where are people spending the most on their taxi trips?
spends_most_on_trips <- "downtown" # "uptown" or "downtown"
```

